# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nginx-new

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f99de7e453374d8fb860ac83004c33f5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a97f2479cd6c48128a0cf3a0523eb455 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f99de7e453374d8fb860ac83004c33f5 }}/josingh2417/nginx-new:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nginx-new'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ff8e27e38eb54f85ba4c47cf7e4cb5b8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f99de7e453374d8fb860ac83004c33f5 }}/josingh2417/nginx-new:${{ github.sha }}'